# Generated by Django 6.0.5 on 2026-06-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(verbose_name='Data do Atendimento')),
                ('descricao', models.TextField(verbose_name='Descrição do Atendimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20, verbose_name='Status do Atendimento')),
                ('tipo_pessoa', models.CharField(choices=[('ALU', 'Aluno'), ('SER', 'Servidor'), ('EXT', 'Usuário Externo')], max_length=3, verbose_name='Tipo de Pessoa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'db_table': 'atendimento',
                'ordering': ['-data_atendimento'],
            },
        ),
    ]
