# Generated by Django 6.0.5 on 2026-06-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateField(verbose_name='Data do Atendimento'),
        ),
    ]
