# Generated by Django 6.0.5 on 2026-06-04 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_responsavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=20, unique=True, verbose_name='SIAPE')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidores', to='usuarios.endereco')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'servidor',
                'ordering': ['nome'],
            },
        ),
    ]
